const { withAppBuildGradle } = require('@expo/config-plugins');

// Release signing for the standalone APK (R1-T1).
//
// Why a config plugin instead of editing android/app/build.gradle directly:
// the whole android/ folder is gitignored and regenerated by `expo prebuild`,
// so any hand edit there is silently wiped on the next prebuild. This plugin
// re-applies the release signing config every time android/ is regenerated.
//
// The actual credentials live OUTSIDE the repo, in ~/.gradle/gradle.properties
// (REFILLIO_RELEASE_* keys). This file references them by name only — it never
// contains the keystore path or password, so it is safe to commit.
//
// The `hasProperty` guard means a machine without those credentials still
// prebuilds fine; only a *release* build on such a machine would fail (there is
// nothing to sign with), which is the correct outcome. Debug builds are
// unaffected.
function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    let gradle = cfg.modResults.contents;

    // 1. Add a `release` entry inside signingConfigs { ... }, right after the
    //    opening brace. Idempotent: skip if it's already there.
    if (!gradle.includes('REFILLIO_RELEASE_STORE_FILE')) {
      gradle = gradle.replace(
        /signingConfigs\s*\{/,
        `signingConfigs {
        release {
            if (project.hasProperty('REFILLIO_RELEASE_STORE_FILE')) {
                storeFile file(REFILLIO_RELEASE_STORE_FILE)
                storePassword REFILLIO_RELEASE_STORE_PASSWORD
                keyAlias REFILLIO_RELEASE_KEY_ALIAS
                keyPassword REFILLIO_RELEASE_KEY_PASSWORD
            }
        }`,
      );
    }

    // 2. Point the release buildType at signingConfigs.release instead of the
    //    default signingConfigs.debug. Anchored on `def enableShrinkResources`,
    //    which appears only in the release buildType, so the debug buildType's
    //    identical line is left alone.
    gradle = gradle.replace(
      /signingConfig signingConfigs\.debug(\s*\n\s*def enableShrinkResources)/,
      'signingConfig signingConfigs.release$1',
    );

    cfg.modResults.contents = gradle;
    return cfg;
  });
}

module.exports = withReleaseSigning;
